---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ['include']

# handlers file for memoryleak.pound
- name: pound-restarted
  service: 
    enabled: Yes
    name: "{{ pound_service }}"
    state: restarted
  tags: ['service']